import { SITE } from '@/lib/site-meta';
// Repo where issues are filed. Reads PUBLIC_REPO_SLUG so a fork reports to its
// own repo (not the template's). Falls back to the template slug for dev.
const REPO = SITE.repoSlug;

export interface ReportIssueInput {
  title: string;
  body?: string;
  labels?: string[];
  /**
   * Issue-form file under `.github/ISSUE_TEMPLATE/` (e.g.
   * `recipe-submission.yml`). Emitted first so the URL reads
   * `issues/new?template=…&…`.
   */
  template?: string;
  /**
   * Issue-form fields prefilled by their `id` (GitHub reads any query
   * parameter named after a field id of the chosen template).
   */
  fields?: Readonly<Record<string, string>>;
}

/**
 * Practical ceiling for a prefilled "new issue" URL. GitHub (and some
 * browsers/proxies) reject or truncate longer request lines, so callers that
 * embed large payloads (the recipe JSON of roadmap Issue 039) must check
 * `issueUrlFits()` and fall back to asking for an attachment.
 */
export const ISSUE_URL_MAX_LENGTH = 8 * 1024;

/**
 * Build a GitHub "new issue" URL pre-filled with the given fields. The
 * page running this code MUST be able to handle redirect navigation; we
 * return the URL string and let the caller decide window.open vs
 * location.assign.
 */
export function buildIssueUrl({ title, body = '', labels = [], template, fields = {} }: ReportIssueInput): string {
  const params = new URLSearchParams();
  if (template) params.set('template', template);
  params.set('title', title);
  if (body) params.set('body', body);
  if (labels.length > 0) params.set('labels', labels.join(','));
  for (const [id, value] of Object.entries(fields)) {
    if (value) params.set(id, value);
  }
  return `https://github.com/${REPO}/issues/new?${params.toString()}`;
}

/** Whether `url` stays under `ISSUE_URL_MAX_LENGTH` (8 KB). */
export function issueUrlFits(url: string): boolean {
  return url.length <= ISSUE_URL_MAX_LENGTH;
}

export function openIssue(input: ReportIssueInput): void {
  openIssueUrl(buildIssueUrl(input));
}

/** Open an already-built issue URL in a new tab (no opener, no referrer). */
export function openIssueUrl(url: string): void {
  if (typeof window === 'undefined') return;
  window.open(url, '_blank', 'noopener,noreferrer');
}

/**
 * Build a body for a runtime error. Includes the error name, message,
 * stack trace (clipped to 50 lines), component path, user agent, and the
 * current URL. Safe to call on server (window/navigator guarded).
 */
export function buildErrorReportBody(args: {
  error: Error;
  componentPath?: string;
  hydrationMismatch?: boolean;
}): string {
  const { error, componentPath, hydrationMismatch } = args;
  const stack = (error.stack ?? 'no stack')
    .split('\n')
    .slice(0, 50)
    .join('\n');
  return [
    '<!-- Auto-generated by FeedbackFAB error boundary -->',
    '',
    `**Type:** ${hydrationMismatch ? 'Hydration mismatch' : 'Runtime error'}`,
    `**Error:** \`${error.name}: ${error.message}\``,
    componentPath ? `**Component path:** \`${componentPath}\`` : '',
    typeof window !== 'undefined' ? `**URL:** ${window.location.href}` : '',
    typeof navigator !== 'undefined' ? `**User agent:** ${navigator.userAgent}` : '',
    '',
    '## Stack',
    '',
    '```',
    stack,
    '```',
  ]
    .filter(Boolean)
    .join('\n');
}
